### ISSUE TITLE
SoftWing on Android 12

### ISSUE THREAD

**Issue by diejuse** [lucasjodon/SoftWing#3]
Works?

**Comment by zoeyjodon** [comment]
Not sure if this works or not yet since I still haven't gotten the upgrade. I would assume it is still compatible since, unlike earlier versions, the current release doesn't depend on the keyboard swapping hack.

I'll come back and update this when I get the upgrade though!

**Comment by zoeyjodon** [comment]
Got the upgrade, and SoftWing still works! It also looks like keyboard swapping is back, so I want to try and re-add key events since they work a little better than touch controls for certain apps.

**Comment by diejuse** [comment]
Great! I couldn't manage it to work. Maybe you could make a demo video

**Comment by zoeyjodon** [comment]
Sure! The Readme for this is overdue for an update anyway

**Comment by zoeyjodon** [comment]
I've just added a demo video for the controller, as well as some bug fixes for Android 12. This should be working now.

**Comment by diejuse** [comment]
Great
